### ISSUE TITLE
[preservation_robots/prod] RuntimeError: version mismatch - current: 1 new: 1

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/preservation_robots#123]
## Backtrace

    line 24 of [PROJECT_ROOT]/robots/preservation_ingest/update_moab.rb: update_moab
    line 17 of [PROJECT_ROOT]/robots/preservation_ingest/update_moab.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/55564/faults/48286435)

**Comment by jcoyne** [comment]
@blalbrit  said:

>this happens when the copy on the deposit folder has been successfully unpacked to a moab on sdr2object directory, but then system is interrupted and tries again
>it’s a manual fix on the pres core. I’ll show Tony Zanella how to do it.

**Comment by andrewjbtw** [comment]
This issue is over a year old and there aren't any more items with this error listed in Argo. It can be closed - I would do it but I don't have permission.
