### ISSUE TITLE
Bag validation errors that are sporadic and go away when reset

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/preservation_robots#176]
**Describe the bug**
Bag validation errors in the `validate-bag` step of `preservationIngestWF` are sporadic and unexplained.  We should investigate root causes.

HB alert: https://app.honeybadger.io/projects/55564/faults/51835368

Examples:
- https://argo.stanford.edu/view/druid:wf806cr4565
MJG re-ran the failed step on 12/5 and the object sailed through its WFs with no errors.

- https://argo.stanford.edu/view/druid:ps821xq8077
This one is ”really puzzling because validate-bag hit an error in the last day but all of the other workflow steps for that object ran 14 days ago (successfully)” (from Andrew). This is… weird. The object that is complaining has already been preserved, which is why its files are missing in the deposit subdirectory; they have already been cleaned up. MJG verified that v4 is already looking good on both the filesystem and the catalog. After consultation with Andrew and John, we agreed to set the remainder of the problematic workflow to completed. The object is no longer in an error state.

**User Impact**
We need to reset the errors and or fix before objects are properly preserved.  This is time consuming.

**To Reproduce**
See the [HB alert](https://app.honeybadger.io/projects/55564/faults/51835368)

**Expected behavior**
Validation should not fail unless something bad actually happened to the content.

**Comment by peetucket** [comment]
Even though the error is triggered by the `validate-bag` robot, the actual validation is done by a class in the [`moab-versioning`](https://github.com/sul-dlss/moab-versioning/blob/master/lib/moab/deposit_bag_validator.rb) gem that is being used by the robot suite

**Comment by peetucket** [comment]
Reproducing validation errors on the command line:

```
# cd into local preservation_robots code
cap prod ssh
ROBOT_ENVIRONMENT=prod bundle exec bin/console
druid='druid:vf742yx0561'
moab_object = Stanford::StorageServices.find_storage_object(druid, true)
deposit_bag_validator = Moab::DepositBagValidator.new(moab_object)
validation_errors = deposit_bag_validator.validation_errors # takes a while
```

**Comment by peetucket** [comment]
The only current one with this error as of 12/11/2019 is `druid:vf742yx0561`, and it is a large 229 GB file whose checksum doesn't match.  Perhaps this a valid failure with the copy from the /dor mount?

**Comment by peetucket** [comment]
There is currently a legitimate mismatch between the file on the `service-disk` and the file on the `/dor/workspace` mount (which currently symlinks to a file on an `/arts/ParkerTransfer` mount).  The file on the `service-disk` has an older timestamp and is 10 GB smaller, so it is expected to have a checksum mismatch, though not clear how this situation came to be.

**Comment by ndushay** [comment]
tagging @andrewjbtw re druid `vf742yx0561` ... can you take it from here, or does it need dev work also?

**Comment by andrewjbtw** [comment]
I don't think that needs dev work at this point. I need to check in with Ben about that object first, as he is the content owner.

**Comment by peetucket** [comment]
All objects remediate except for vf742yx0561, which Ben is working on.  Could not find root cause for these failures.  Closing for now and will be opened if we see this continuing to create new errors.
