### ISSUE TITLE
(IR) is there a good way to cache the storage root / deposit bag pathname across robots? (blocked by #22)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#21]
When all is well, and the robots all execute sequentially without a failure, they are often instantiating a Moab object (via Sdr::Replication in sdr-replication gem for unknown reasons) ... the SAME moab object every time.

it would be grand if they didn't have to discover which storage root every time.
it would be grander if information we need from moab could be cached so we didn't even have to instantiate the moab if all we need, for example, is deposit-bag-pathname.

**Comment by ndushay** [comment]
Experiment with class-cache-experiment cache;  consider some way to use Base robot for this???

**Comment by ndushay** [comment]
created a branch class-cache-experiment to try this, once we have #22

**Comment by atz** [comment]
Not being entirely familiar w/ the problem described, I think I would still be willing to apply some effort here if you could identify 2 lines of code (in different robots) that would conceivably be reusing the same cached data/object.

**Comment by ndushay** [comment]
This should be done w memcache rather than memoization;  a memory based cache rather than ruby class memoization due to some sidekiq stuff about memoization and thread safety, etc.
