### ISSUE TITLE
SDRGET script hits errors when the same file appears mutliple times in contentMetadata

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_robots#211]
**Describe the bug**
The create_bag.rb script fails on certain druids. I think this may be related to how Moabs handle duplicate content files.

For example, create_bag fails on https://argo.stanford.edu/view/qp900xz3678 with the following error:

```
Traceback (most recent call last):
        3: from create_bag.rb:29:in `<main>'
        2: from create_bag.rb:29:in `each'
        1: from create_bag.rb:30:in `block in <main>'
create_bag.rb:36:in `rescue in block in <main>': uninitialized constant ObjectNotFoundException (NameError)
```
This item contains one file named qp900xz3678.pdf that is listed twice in the content metadata, first as a page and then as the whole object (which is one page). It's possible that the script is trying to place the file in the bag twice and encountering an error the second time because a file already exists at that path.

**User Impact**
It is not possible to do an automated SDRGET for objects that throw this error.

**To Reproduce**
1. ssh into preservation_robots
2. `cd preservation_robots/current/bin`
3. `touch /tmp/druids.txt # add "druid:qp900xz3678" to this file`
4. `mkdir /tmp/SDRGET # where the bag will be placed`
5. `ruby create_bag.rb /tmp/druids.txt /tmp/SDRGET`
6. see the error

**Comment by tallenaz** [comment]
If I run through the steps of the script in the console, I see the error message:

```
[10] pry(main)> storage_object.reconstruct_version(version_id, bag_dir)
Errno::EEXIST: File exists @ syserr_fail2_in - /opt/app/pres/preservation_robots/current/bin/tmp/SDRGET/bags/druid:qp900xz3678/data/content/qp900xz3678.pdf
from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/fileutils.rb:323:in `symlink'
```

**Comment by tallenaz** [comment]
Verified that the above error message is thrown at https://github.com/sul-dlss/moab-versioning/blob/9e24a35624b0c54c94a0386e1de7cbf52cf5b0d3/lib/moab/storage_object.rb#L109

when the version reconstruction's `Bagger` object tries to `fill_bag`.

**Comment by tallenaz** [comment]
bug fix release https://github.com/sul-dlss/moab-versioning/commit/56945fb15cceb7a12876e71a60d857c793577c29 should roll out to pres robots Monday.

**Comment by andrewjbtw** [comment]
Confirming this is fixed. I ran the same druids recently without a problem.
