### ISSUE TITLE
preservationIngestWF is a bottleneck to large-scale accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_robots#212]
The preservationIngestWF can get backed up when a high volume of data is going through it. It took only about an hour for a queue to build up like this:

<img width="1272" alt="Screen Shot 2020-04-10 at 1 12 40 AM" src="https://user-images.githubusercontent.com/8975583/78975434-f030cf80-7ac8-11ea-9794-fb61a24c4d1d.png">

It's worth noting that this is mostly not Google Books. I suspect the issue is I/O related and more likely to come up with large files rather than lots of small files. The preservationIngestWF involves some long read-write operations - transferring files and checking checksums.

**Comment by andrewjbtw** [comment]
Additional bit of information per conversation with @julianmorley:

Scaling this workflow will be more complicated than simply adding another preservation-robot box because of how the file I/O will need to be handled.

I don't know more detail than that at this point. I'm leaving the note here so we don't lose sight of it when/if this ticket gets picked up.

**Comment by ndushay** [comment]
@andrewjbtw is this still a problem, or would you like to close the ticket?

**Comment by andrewjbtw** [comment]
More of a potential problem than when it was filed (fewer workers) but less of an actual problem because google goes into a different lanes now and the big media backlog accessioning of 2018-2020 has ended.

To put it another way, I'll close it and we can file another issue if it becomes an ongoing problem and not a potential one.
