### ISSUE TITLE
(IR) add cap deployment for robots (need new robot VMs)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/preservation_robots#22]
As a maintainer on the infrastructure team
I would like to know how to deploy preservation_robots
So that I can fix security issues when github detects them.

Capistrano fulfills this role in other projects and would be the consistent choice.

**Comment by ndushay** [comment]
somewhat blocked until we have new robot VMs

**Comment by ndushay** [comment]
done in runnable branch as far as possible without new robot VMs

**Comment by tallenaz** [comment]
See https://github.com/sul-dlss/preservation_robots/pull/31 that gets the runnable branch deployable
