### ISSUE TITLE
Proxy: work w/ ops to resolve pres robots transfer-object communication issue

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_robots#238]
Proxy for ops-task ticket to replace lyberservices with dor-services for transfer-object step
https://github.com/sul-dlss/operations-tasks/issues/2261

**Comment by jmartin-sul** [comment]
i added pres robots to the zenhub board (because we'll have an issue or two in there re: supporting multiple copies of a moab for a druid).  so i went ahead and transferred this issue to that repo, to remove a bit of indirection.

**Comment by ndushay** [comment]
I left notes on sul-dlss/operations-tasks#2261 that the ticket can be closed.
