### ISSUE TITLE
(IR) re-implement weekly_status script in preservation_robots

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#24]
@blalbrit mentioned that in the `bin/` directory, the script `weekly_status.sh` should be brought over because it is used by ...?

Not sure if I have this right.

I imagine there is a need for a rewrite of that script, too.

**Comment by blalbrit** [comment]
I think the weekly_status is what's used, but @tallenaz can confirm.

**Comment by tallenaz** [comment]
Yes, it's the `weekly_status.sh` that's needed.

**Comment by atz** [comment]
Please endeavor to make as much logic as possible testable code and not leaf-node one-off scripting.
