### ISSUE TITLE
pres robots asks pres cat about druid to be updated, deals w/ 4xx responses properly

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_robots#249]
pres robots should be able to ask for the location of the primary moab from pres cat.

* if it gets a 423, abort the update.  this indicates that pres cat knows about the druid already, and that updates of any of the associated moabs are disabled for the time being
* if it gets a 404, and there's only one moab in the storage roots, this indicates that pres cat doesn't yet know about the druid, as when it's first being accessioned, and that pres robots can just update the one copy of the moab that exists
* if it gets a 404, but there are multiple copies of the moab among the storage roots, that means that we don't have sufficient information on which moab is the primary, and we should abort the update, investigate, and fix our bad data.  i think letting the robot update fail and issue a honeybadger alert should be fine for this case.

let's pair if any of the above is unclear, just getting this filed while also being half distracted by in progress CentOS 7 migration for preservation stack.

see also #239, https://github.com/sul-dlss/preservation_catalog/issues/1598

**Comment by ndushay** [comment]
@jmartin-sul can this be closed, as it is about multiple moab instances?
