### ISSUE TITLE
set up shadynet / NAT'd IP address for prod machines

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_robots#46]

**Comment by tallenaz** [comment]
see https://github.com/sul-dlss/preservation_catalog/issues/173#issuecomment-375552027

**Comment by tallenaz** [comment]
We don't yet have a general purpose shadynet range, just something for one service right now.

**Comment by ndushay** [comment]
@tallenaz should this ticket be closed?

**Comment by tallenaz** [comment]
I think this one should stay in the backlog.

**Comment by jmartin-sul** [comment]
@tallenaz, should this stay open?
