### ISSUE TITLE
Deposit is stuck in accessioning; hidden MacOS "Icon" files are probably to blame

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_robots#540]
This H2 deposit has hit an error at `validate-bag` because there's a problem validating the file transfer from the /dor/workspace to the preservation mount: https://argo.stanford.edu/view/druid:sg697rz2807

The error message is:
```
Error: validate-bag : Bag validation failure(s) for druid:sg697rz2807: 
[{:checksum_mismatch=>"Failed manifest verification. 

Differences: \n{\"data/content/CoronavirusSL5-M2seq_UBR_output/Figures/Icon"=>
{:sha256=>{\"manifest\"=>\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\", \"generated\"=>nil}, 
:sha1=>{\"manifest\"=>\"da39a3ee5e6b4b0d3255bfef95601890afd80709\", \"generated\"=>nil}, 
:md5=>{\"manifest\"=>\"d41d8cd98f00b204e9800998ecf8427e\", \"generated\"=>nil}}, 

\"data/content/CoronavirusSL5-M2seq_UBR_output/Figures/Icon\\r\"=>
{:sha256=>{\"manifest\"=>nil, 
\"generated\"=>\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\"}, 
:sha1=>{\"manifest\"=>nil, \"generated\"=>\"da39a3ee5e6b4b0d3255bfef95601890afd80709\"}, 
:md5=>{\"manifest\"=>nil, \"generated\"=>\"d41d8cd98f00b204e9800998ecf8427e\"}}}"}]
```
I think that message means:

- There's a file called `Icon` in the manifest but it can't be found on the filesystem: `\"generated\"=>nil`
- There's a file on the filesystem called `Icon\r` but it can't be found in the manifest: `\"manifest\"=>nil`

The problem seems to be that MacOS "Icon" files include a carriage return in the filename and that's causing a mismatch between what's in the manifest file and what's on the filesystem.

**Proposal**

We should sidestep this issue by excluding MacOS `Icon` files from accessioning. These are similar to `.DS_Store` files and other MacOS-specific files that become filesystem clutter when on non-Mac filesystems. We already exclude `.DS_Store` and other files, so I'm not sure why we don't exclude `Icon` files already. These files have to do with the appearance of icons in MacOS (desktop and finder displays?). If you look at the `Icon` files that are in this accession, they are actually empty and provide no value. So including them is only causing accessioning to stall.

**Comment by jmartin-sul** [comment]
transferring this to pres robots, as i believe it's an issue there.  will transfer back to H2, or the appropriate repo, if that ends up being wrong

**Comment by jmartin-sul** [comment]
i think i reproduced this (or very similar) in H2 stage:
* https://argo-stage.stanford.edu/view/bp823jx3060
* https://sdr-stage.stanford.edu/works/200

**Comment by jmartin-sul** [comment]
After much discussion and testing, the plan is:
* @andrewjbtw is editing this object to not have reference to the `Icon\r` files in cocina structural metadata.  He's also removed them from the `/dor/workspace` files and removed the bag from the pres deposit space.  He's manually removed `accessionWF` and `preservationWF`, and re-added `accessionWF` manually.  The object is now making its way through accessioning again, sans empty MacOS `Icon\r` files.
* @andrewjbtw will also verify the integrity of the accessioned object once it's landed.
* and he'll file a ticket to block deposits that have files with control characters in any file names (or just ignore such files in H2?)
* the pres robots work to get files like this through `preservationIngestWF` has been scrapped, see explanation here: https://github.com/sul-dlss/preservation_robots/pull/541#issuecomment-1974251234

**Comment by andrewjbtw** [comment]
We decided not to go down the path of accepting the `Icon\r` filename or any other filename with control characters in it. Instead, I will file a new issue to filter out `Icon\r` files like we do with `.DS_Store`
