### ISSUE TITLE
(R) can resque serve as zip creation non-dup

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#59]
There is a way to use a resque extension to do this;  we don't need to roll our own write locks or what have you;  we  can configure a redis queue  to be blocking and have the worker's first step be "does this file already exist?"

**Comment by SaravShah** [comment]
https://github.com/defunkt/resque-lock

**Comment by ndushay** [comment]
In wrong repo;  closed in favor of sul-dlss/preservation_catalog/issues/677
