### ISSUE TITLE
(IR) pres-robots shared_configs updated for pres_cat url

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#61]
update-catalog robot (from #7) needs to interact with the appropriate preservation catalog url;   presumably a setting needs to be added to shared_configs  config/environments/stage.yml  and  .../prod.yml  for this

**Comment by atz** [comment]
According to puppet those values are:
- preservation-catalog-prod.stanford.edu
- preservation-catalog-stag.stanford.edu

**Comment by atz** [comment]
PRs:
https://github.com/sul-dlss/shared_configs/pull/538
https://github.com/sul-dlss/shared_configs/pull/539
