### ISSUE TITLE
(IR) add "lanes" to prod preservation robots

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#66]
@blalbrit  - it looks like current production preservation robots (sdrIngestWF) have lanes; do the new robots also need to be configured with lanes?

![image](https://user-images.githubusercontent.com/96775/38901887-e7a3db2e-4252-11e8-917e-e714d0ac6ac4.png)

**Comment by blalbrit** [comment]
@ndushay - the lanes were put in place with the intention that if we hit capacity (or were moving lots of low-priority objects into the repository) we could assign priorities. We have not been using them regularly, but are starting to receive very large projects from third parties and from the media lab that might make this a desirable behavior to maintain.

If you *can* keep the lanes, I think we will use them.

**Comment by ndushay** [comment]
I believe this requires updating some robots.yml  in config -- possibly in robots app;  possibly in shared_configs.   Look up the same for sdr-preservation-core and make the adjustments.
