### ISSUE TITLE
(IR) addl nagios checks - e.g. do  we want to have a nagios check for connectivity to /dor/export

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#74]
From old robots on sul-sdr-services, the cron has

```
# Every 15 minutes, test the connectivity of SDR-PC to /dor/export
#*/15 * * * *  $HOME/bin/sdr-verify-versionMetadata.sh testTransfers/bb335qc9336
```

I'm guessing if we want to test connectivity to /dor/export from the robots VM, we could do it more simply via nagios?  (check that a mounted drive is avail?)

Tony wonders if there already a nagios check we can use.

See

https://github.com/sul-dlss/puppet/blob/production/hieradata/node/was-robots1-prod.stanford.edu.eyaml#L100-L124

**Comment by tallenaz** [comment]
The script that tested connectivity to /dor/export only ever generates an exit code that AFAICT nothing ever cared about. @ndushay notes that if there's a connectivity problem here the transfer-object robot will fail, which will then cause the robot suite to alert. I'm making the call that we don't want to recreate the script's functionality.

The storage mount on sdr-services-test will now alert at 80%
