### ISSUE TITLE
(IR) daily activity scripts should be combined

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#86]
per @blalbrit, it would be ideal to combine the error_reporter and the activity_reporter into a single "daily_reporter" script.  It would provide the following for each robot:

- successfully processed druid counts
- errors reported
- warnings reported

It wouldn't surprise me if @blalbrit would like to have the druids for each warning and error - not sure how good a job we are doing of including it in those log messages.   I strongly suggest conferring with him on what would truly be the most useful.

Ideally, it would use a regex to find the individual robot logs, as that would make the reports more future-proof if the steps in the preservationIngestWF change (See #85).

**Comment by atz** [comment]
Both logging and these reports have changed w/ feedback from Ben in the intervening 5 months, including very recently.
